import asyncio
import random
from agents import Agent, ItemHelpers, Runner, function_tool
from dotenv import load_dotenv

load_dotenv(override=True)

# ============================================================
# 🔧 TOOL
# ============================================================
@function_tool
def how_many_jokes() -> int:
    return random.randint(1, 10)


# ============================================================
# 🤖 AGENT
# ============================================================
# This agent:
# 1. Calls the tool first
# 2. Then generates jokes based on tool output
agent = Agent(
    name="Joker",
    instructions="Call how_many_jokes first, then tell that many jokes.",
    tools=[how_many_jokes],
)


# ============================================================
# 🚀 MAIN STREAMING FUNCTION
# ============================================================
async def main():

    # Start streaming run
    result = Runner.run_streamed(agent, input="Hello")

    print("=== Run starting ===")

    # ========================================================
    # 🔁 STREAM EVENTS LOOP
    # ========================================================
    async for event in result.stream_events():

        # ----------------------------------------------------
        # 1️⃣ RAW TOKEN STREAM (LOW LEVEL)
        # ----------------------------------------------------
        if event.type == "raw_response_event":
            # This gives token-by-token output (like typing effect)
            # We skip it here to avoid messy logs
            continue


        # ----------------------------------------------------
        # 2️⃣ AGENT SWITCH EVENT (HANDOFF)
        # ----------------------------------------------------
        elif event.type == "agent_updated_stream_event":
            print(f"Active agent: {event.new_agent.name}")


        # ----------------------------------------------------
        # 3️⃣ HIGH-LEVEL EVENTS (MOST USEFUL)
        # ----------------------------------------------------
        elif event.type == "run_item_stream_event":

            # item = what just finished (message/tool/etc.)
            item = event.item

            # 🛠 Tool call started
            if item.type == "tool_call_item":
                print("⚙️ Tool was called")

            # ✅ Tool finished execution
            elif item.type == "tool_call_output_item":
                print(f"✅ Tool output: {item.output}")

            # 💬 Full message generated by LLM
            elif item.type == "message_output_item":
                print(f"💬 Message:\n{ItemHelpers.text_message_output(item)}")


    print("=== Run complete ===")


# ============================================================
# ▶️ RUN
# ============================================================
asyncio.run(main())

# ============================================================
# 🧠 STREAMING EVENTS SUMMARY
# ============================================================

# Runner.run_streamed() gives real-time execution events.

# EVENT TYPES:

# 1️⃣ raw_response_event
# - Fires for every token (word/character)
# - Used for live typing UI
# - Too detailed for logic

# 2️⃣ run_item_stream_event
# - Fires when a full step completes
# - Includes:
#   ✔ message_output_item (final message)
#   ✔ tool_call_item (tool started)
#   ✔ tool_call_output_item (tool finished)
# - Best for logs and progress updates

# 3️⃣ agent_updated_stream_event
# - Fires when agent changes (handoff)
# - Useful in multi-agent systems

# ============================================================
# 💡 BEST PRACTICE
# ============================================================

# ✔ Use raw_response_event → UI streaming (typing effect)
# ✔ Use run_item_stream_event → logs/status updates
# ✔ Use agent_updated_stream_event → agent switching display

# Example UI:
# "Typing..."
# "Calling tool..."
# "Tool finished"
# "Switching agent..."

# ============================================================
